version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    groups:
      bun-npm:
        patterns: ["*"]
    commit-message:
      prefix: chore
    labels: [dependencies, javascript]

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      actions:
        patterns: ["*"]
    commit-message:
      prefix: ci
    labels: [dependencies, github-actions]
